spring:
  application:
    name: config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  cloud:
    config:
      server:
        git:
          uri: https://github.com/QiaoYingD/config-repo
          username: 1974218313@qq.com
          password: q.13949162154
server:
  port: 8090
